# Generated by Django 3.1 on 2020-09-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(db_index=True, max_length=100)),
                ('link', models.CharField(db_index=True, max_length=500)),
            ],
        ),
    ]
