# Generated by Django 3.1 on 2020-09-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20200911_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='social',
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(choices=[('Editor-in-Chief', 'Editor-in-Chief'), ('Writer', 'Writer'), ('Editor', 'Editor'), ('Reporter', 'Reporter'), ('Artist', 'Artist'), ('Developer', 'Developer')], db_index=True, max_length=100),
        ),
    ]
