# Generated by Django 3.1 on 2020-09-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20200911_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='bio',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
