# Generated by Django 3.1 on 2020-09-01 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='related_article',
        ),
    ]
