# Generated by Django 3.1 on 2020-09-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_category_related_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='headline',
        ),
        migrations.RemoveField(
            model_name='article',
            name='related_category',
        ),
        migrations.AddField(
            model_name='article',
            name='related_category',
            field=models.ManyToManyField(to='article.Category'),
        ),
    ]
