# Generated by Django 3.1 on 2020-09-08 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
        ('article', '0003_auto_20200901_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='article/static/article/media/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(upload_to='article/static/article/thumbnail/'),
        ),
        migrations.CreateModel(
            name='Stream_Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.creator')),
            ],
        ),
    ]
