# Generated by Django 3.1 on 2020-09-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200908_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_published',
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='stream_highlight',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stream_highlight',
            name='headline',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stream_highlight',
            name='image',
            field=models.ImageField(null=True, upload_to='article/static/article/media/'),
        ),
        migrations.AddField(
            model_name='stream_highlight',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='stream_highlight',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stream_highlight',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='article/static/article/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='article/static/article/media/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='article/static/article/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
