# Generated by Django 3.1 on 2020-09-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200909_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='headline',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='streamhighlight',
            old_name='headline',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='article/images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='article/thumbnail'),
        ),
        migrations.AlterField(
            model_name='streamhighlight',
            name='image',
            field=models.ImageField(null=True, upload_to='article/images'),
        ),
        migrations.AlterField(
            model_name='streamhighlight',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='article/thumbnail'),
        ),
    ]
