# Generated by Django 3.1 on 2020-09-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20200911_1403'),
        ('article', '0007_auto_20200911_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contributors',
            field=models.ManyToManyField(to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='streamhighlight',
            name='contributors',
            field=models.ManyToManyField(to='staff.Staff'),
        ),
    ]
