# Generated by Django 3.1 on 2020-09-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20200911_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('News', 'News'), ('Events', 'Events'), ('SMPs', 'SMPs'), ('Discover', 'Discover')], db_index=True, max_length=100, null=True),
        ),
    ]
