# Generated by Django 3.1 on 2020-09-11 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20200911_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='article/images')),
                ('description', models.CharField(max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='streamhighlight',
            name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('All', 'All'), ('News', 'News'), ('Events', 'Events'), ('SMPs', 'SMPs'), ('Discover', 'Discover')], db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.image'),
        ),
        migrations.AddField(
            model_name='streamhighlight',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.image'),
        ),
    ]
