# Generated by Django 3.1 on 2020-09-11 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20200911_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
        migrations.RemoveField(
            model_name='streamhighlight',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
