# Generated by Django 3.1 on 2020-09-12 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20200911_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='article/images')),
                ('description', models.CharField(max_length=500, null=True, unique=True)),
                ('related_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.streamhighlight')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='article/images')),
                ('description', models.CharField(max_length=500, null=True, unique=True)),
                ('related_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
        ),
    ]
