# Generated by Django 3.1 on 2020-09-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.CharField(db_index=True, max_length=100)),
                ('profile_pic', models.ImageField(upload_to='creator/static/creator/profile_pic/')),
                ('twitch_link', models.CharField(db_index=True, max_length=500)),
            ],
        ),
    ]
