# Generated by Django 3.1 on 2020-09-02 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('date_published', models.DateField(auto_now_add=True, db_index=True)),
                ('cover', models.ImageField(upload_to='static/magazine/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, unique=True)),
                ('related_magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.magazine')),
            ],
        ),
    ]
