# Generated by Django 3.1 on 2020-09-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='magazine_file',
            field=models.FileField(null=True, upload_to='static/magazine/pdf_files/'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='cover',
            field=models.ImageField(upload_to='static/magazine/covers/'),
        ),
    ]
