# Generated by Django 3.1 on 2020-09-09 18:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0011_auto_20200909_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='cover',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/static/magazine/covers'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='magazine_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/static/magazine/pdf_files'), upload_to=''),
        ),
    ]
