# Generated by Django 3.1 on 2020-09-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0014_auto_20200909_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='magazine_file',
            field=models.FileField(null=True, upload_to='magazine/pdf_files'),
        ),
    ]
